In [28]:
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", None)
import matplotlib.pyplot as plt

In [29]:
dataset = pd.read_csv("processed_train.csv")
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 42 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Id          137 non-null    int64  
 1   Open Date   137 non-null    int64  
 2   City Group  137 non-null    int64  
 3   Type        137 non-null    int64  
 4   P1          137 non-null    int64  
 5   P2          137 non-null    float64
 6   P3          137 non-null    float64
 7   P4          137 non-null    float64
 8   P5          137 non-null    int64  
 9   P6          137 non-null    int64  
 10  P7          137 non-null    int64  
 11  P8          137 non-null    int64  
 12  P9          137 non-null    int64  
 13  P10         137 non-null    int64  
 14  P11         137 non-null    int64  
 15  P12         137 non-null    int64  
 16  P13         137 non-null    float64
 17  P14         137 non-null    int64  
 18  P15         137 non-null    int64  
 19  P16         137 non-null    i

In [30]:
print(dataset.head())

   Id  Open Date  City Group  Type  P1   P2   P3   P4  P5  P6  P7  P8  P9  \
0   0       1999           0     2   4  5.0  4.0  4.0   2   2   5   4   5   
1   1       2008           0     1   4  5.0  4.0  4.0   1   2   5   5   5   
2   2       2013           1     2   2  4.0  2.0  5.0   2   3   5   5   5   
3   3       2012           1     2   6  4.5  6.0  6.0   4   4  10   8  10   
4   4       2009           1     2   3  4.0  3.0  4.0   2   2   5   5   5   

   P10  P11  P12  P13  P14  P15  P16  P17  P18  P19  P20  P21  P22  P23  P24  \
0    5    3    5  5.0    1    2    2    2    4    5    4    1    3    3    1   
1    5    1    5  5.0    0    0    0    0    0    3    2    1    3    2    0   
2    5    2    5  5.0    0    0    0    0    0    1    1    1    1    1    0   
3   10    8   10  7.5    6    4    9    3   12   20   12    6    1   10    2   
4    5    2    5  5.0    2    1    2    1    4    2    2    1    2    1    2   

   P25  P26  P27  P28  P29  P30  P31  P32  P33  P34  P35

In [31]:
X_train = dataset.iloc[:, 1:-1].values
y_train = dataset.iloc[:, -1].values

In [32]:
print(X_train.shape)
print(y_train.shape)

(137, 40)
(137,)


In [33]:
print(len(X_train[0]))

40


In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

# With OUR_OWN_MODEL

In [35]:
from linear_scratch import LinearRegression

linear_regressor = LinearRegression(lr=0.0001, n_iters=10000)
linear_regressor.fit(X_train, y_train)

In [36]:
linear_regressor.predict(X_train)

array([3862675.6147185 , 3199169.55162581, 1812772.23932892,
        553156.48441622, 2032786.80401043, 3941204.47292003,
       2628568.50534307, 3065429.66268009, 1387177.33359551,
       1808255.17185237, 3350738.31079429, 2501251.43304818,
       1859874.57055866, 3076647.66549428, 1868152.84766392,
       2110695.74691134, 4591171.38508465, 3231379.57125691,
       2255479.95116135, 2067574.61058647, 2239398.18625452,
       2945464.68539956, 2640580.13234153, 2789859.34026159,
       3240425.8701627 , 2266135.63488994, 2969725.55866808,
       4051065.79504009, 4359135.41599587, 2957284.03195802,
       1622700.03534923, 2409877.05977174, 2643061.52287104,
       1782053.42787595, 3066846.57509735, 4154571.83198663,
       3384111.86372617, 2279505.09915456, 3375256.01766759,
       3236568.57669803, 3447302.56376584, 3744169.16625636,
       3080033.75116502, 2818663.01829644, 3027783.35470487,
       2150000.28910046, 2448011.90136029, 3255744.2228032 ,
       2674265.82805258,

In [37]:
predictions = linear_regressor.predict(X_train)

print(np.concatenate((y_train.reshape(-1,1), predictions.reshape(-1,1)), axis=1))

[[ 5653753.          3862675.6147185 ]
 [ 6923131.          3199169.55162581]
 [ 2055379.          1812772.23932892]
 [ 2675511.           553156.48441622]
 [ 4316715.          2032786.80401043]
 [ 5017319.          3941204.47292003]
 [ 5166635.          2628568.50534307]
 [ 4491607.          3065429.66268009]
 [ 4952497.          1387177.33359551]
 [ 5444227.          1808255.17185237]
 [ 3745135.          3350738.31079429]
 [ 5161370.          2501251.43304818]
 [ 1734634.          1859874.57055866]
 [ 4807746.          3076647.66549428]
 [ 1999097.          1868152.84766392]
 [ 3218918.          2110695.74691134]
 [19696939.          4591171.38508465]
 [ 8213524.          3231379.57125691]
 [ 5337526.          2255479.95116135]
 [ 2021934.          2067574.61058647]
 [ 5525735.          2239398.18625452]
 [ 1149870.          2945464.68539956]
 [ 3956086.          2640580.13234153]
 [ 2999068.          2789859.34026159]
 [ 8904084.          3240425.8701627 ]
 [ 3778621.          2266

In [38]:
from sklearn.metrics import mean_squared_error

mse_train = mean_squared_error(y_train, predictions)
print(mse_train)

7982421711017.063


# With SKLEARN

In [39]:
from sklearn.linear_model import LinearRegression

regressor_sk = LinearRegression()

regressor_sk.fit(X_train, y_train)

LinearRegression()

In [40]:
regressor_sk.predict(X_train)

array([6886267.97159433, 5322137.46996486, 2893768.41262468,
       3981643.61490485, 3486080.88728309, 6474874.08040399,
       4388239.81953308, 3610134.0431247 , 3951436.39349757,
       3051089.22214775, 6328115.82285075, 5254724.60002697,
       2018727.02589726, 4477992.4225517 , 2434562.0902433 ,
       3703721.73744747, 8258507.56151683, 5500789.12284652,
       2613128.2733489 , 3427280.24663754, 6481959.06386474,
       3895824.04506936, 4172924.31506163, 5367654.0296344 ,
       6643998.94751045, 4491976.49337663, 4795574.6010644 ,
       5628590.10492339, 5489916.86217021, 3906140.85678957,
       2265288.29937635, 2011263.4035422 , 4459756.05012046,
       3275133.22348628, 4388142.78519468, 5482986.99522054,
       4452208.46977388, 4749432.42285903, 6294175.29204949,
       3451735.07531247, 6728922.15462536, 5246425.8316755 ,
       5053185.47099826, 3785839.93539695, 5471640.93639043,
       1904430.60295407, 3545300.94765195, 7412425.24905459,
       3866957.24670637,

In [41]:
predictions_sk = regressor_sk.predict(X_train)

print(np.concatenate((y_train.reshape(-1,1), predictions_sk.reshape(-1,1)), axis=1))

[[ 5653753.          6886267.97159433]
 [ 6923131.          5322137.46996486]
 [ 2055379.          2893768.41262468]
 [ 2675511.          3981643.61490485]
 [ 4316715.          3486080.88728309]
 [ 5017319.          6474874.08040399]
 [ 5166635.          4388239.81953308]
 [ 4491607.          3610134.0431247 ]
 [ 4952497.          3951436.39349757]
 [ 5444227.          3051089.22214775]
 [ 3745135.          6328115.82285075]
 [ 5161370.          5254724.60002697]
 [ 1734634.          2018727.02589726]
 [ 4807746.          4477992.4225517 ]
 [ 1999097.          2434562.0902433 ]
 [ 3218918.          3703721.73744747]
 [19696939.          8258507.56151683]
 [ 8213524.          5500789.12284652]
 [ 5337526.          2613128.2733489 ]
 [ 2021934.          3427280.24663754]
 [ 5525735.          6481959.06386474]
 [ 1149870.          3895824.04506936]
 [ 3956086.          4172924.31506163]
 [ 2999068.          5367654.0296344 ]
 [ 8904084.          6643998.94751045]
 [ 3778621.          4491

In [42]:
from sklearn.metrics import mean_squared_error

mse_sk = mean_squared_error(y_train, predictions_sk)
print(mse_sk)

4319040910230.0757


In [43]:
mse_train < mse_sk

False

# With TEST data

In [44]:
test_dataset = pd.read_csv("processed_test.csv")
print(test_dataset.head())

   Id  Open Date  City Group  Type  P1   P2   P3   P4  P5  P6  P7  P8  P9  \
0   0       2011           1     1   1  4.0  4.0  4.0   1   2   5   4   5   
1   1       2011           1     2   3  4.0  4.0  4.0   2   2   5   3   4   
2   2       2013           0     1   3  4.0  4.0  4.0   2   2   5   4   4   
3   3       2013           1     2   2  4.0  4.0  4.0   2   3   5   4   5   
4   4       2013           1     1   2  4.0  4.0  4.0   1   2   5   4   5   

   P10  P11  P12  P13  P14  P15  P16  P17  P18  P19  P20  P21  P22  P23  P24  \
0    5    5    3  4.0    0    0    0    2    0    5    5    3    1    4    0   
1    4    2    4  5.0    0    0    0    0    0    5    5    3    2    1    0   
2    5    4    5  5.0    0    0    0    0    0    5    5    5    5    5    0   
3    4    3    4  5.0    0    0    0    0    4    4    4    3    2    2    0   
4    4    3    5  4.0    0    0    0    0    0    1    5    3    1    1    0   

   P25  P26  P27  P28  P29  P30  P31  P32  P33  P34  P35

In [45]:
X_test = test_dataset.iloc[:, 1:].values

In [46]:
X_test = scaler.transform(X_test)

In [47]:
test_predictions = linear_regressor.predict(X_test)
print(test_predictions)

[2699493.38297374 2095651.80441223 2748122.01245086 ... 3043878.98764644
 2905624.61890897 2940490.92619921]
